import { GOLDEN_TIME_PROFILE } from './golden-time-profile.js?v=step6d';
import { getTreasureContinuationPct, rollTreasureContinuation } from './treasure-profile.js?v=step6d';
import { LUPIN_RUSH_PROFILE, getLupinRushType } from './lupin-rush-profile.js?v=step6d';
import { ART_STAGE_PROFILE, getArtStage, rollStageTreasureHit } from './art-stage-profile.js?v=step6d';

export class GoldenTimeSystem {
  constructor(rng){this.rng=rng;this.reset();}
  reset(){this.state='IDLE';this.setNo=0;this.gameInSet=0;this.remainingGames=null;this.guaranteedStocks=0;this.entrySource=null;this.lastEvent=null;this.result='UNRESOLVED';this.treasurePoints=0;this.battleContinuationPct=null;this.battleResult=null;this.battleSource=null;this.rushGameCount=0;this.rushRemainingGames=null;this.rushType=null;this.rushTypeAverageTreasure=null;this.rushResultSource=null;this.stage=null;this.stageSource=null;this.stageTreasureHitEvents=0;this.lastStageTreasureHitGame=null;this.pendingTreasureAwardEvents=0;this.ikukanGameCount=0;this.ikukanRemainingGames=null;this.ikukanGuaranteedMinimumAccrued=0;}
  start({guaranteedStocks=0,source='DEBUG_DIRECT_ENTRY'}={}){this.reset();this.state='LUPIN_RUSH_ACTIVE';this.setNo=1;this.guaranteedStocks=Math.max(0,Number(guaranteedStocks)||0);this.entrySource=source;this.lastEvent='LUPIN_RUSH_START';this.rushRemainingGames=LUPIN_RUSH_PROFILE.games;this.rushResultSource='PENDING_UNVERIFIED_SELECTION_DISTRIBUTION';return true;}
  addStocks(count,source='DEBUG_ONLY'){if(this.state==='IDLE')return false;const add=Math.max(0,Number(count)||0);this.guaranteedStocks+=add;this.lastEvent=`GT_STOCK_PLUS_${add}_${source}`;return true;}
  setTreasureForTest(points){if(this.state==='IDLE')return false;const pct=getTreasureContinuationPct(points);if(pct==null)return false;this.treasurePoints=Number(points);this.battleContinuationPct=pct;this.lastEvent=`DEBUG_TREASURE_SET_${points}`;return true;}
  applyLupinRushAverageForTest(type){if(this.state!=='RUSH_RESULT_PENDING')return false;const row=getLupinRushType(type);if(!row)return false;this.rushType=type;this.rushTypeAverageTreasure=row.averageTreasure;this.rushResultSource='DEBUG_APPLIED_VERIFIED_TYPE_AVERAGE_NOT_ACTUAL_DISTRIBUTION';this.treasurePoints=row.averageTreasure;this.battleContinuationPct=getTreasureContinuationPct(this.treasurePoints);this.state='STAGE_PENDING_SELECTION_MODEL';this.lastEvent=`DEBUG_LUPIN_RUSH_${type}_AVERAGE_APPLIED_STAGE_PENDING`;return true;}
  setStageForTest(stage){if(!['STAGE_PENDING_SELECTION_MODEL','ACTIVE_SET'].includes(this.state))return false;const row=getArtStage(stage);if(!row)return false;this.stage=stage;this.stageSource='DEBUG_SELECTED_VERIFIED_STAGE_NOT_REAL_DISTRIBUTION';this.ikukanGameCount=0;this.ikukanRemainingGames=row.special?row.durationGames:null;if(this.state==='STAGE_PENDING_SELECTION_MODEL'){this.state='ACTIVE_SET';this.gameInSet=0;this.remainingGames=GOLDEN_TIME_PROFILE.setGamesApprox;}this.lastEvent=`DEBUG_GT_STAGE_${stage}`;return true;}
  processStageTreasure(){if(!this.stage)return;const row=getArtStage(this.stage);if(!row)return;if(rollStageTreasureHit(this.stage,this.rng)){this.stageTreasureHitEvents+=1;this.lastStageTreasureHitGame=this.gameInSet;if(row.special){this.ikukanGameCount+=1;this.ikukanRemainingGames=Math.max(0,row.durationGames-this.ikukanGameCount);this.ikukanGuaranteedMinimumAccrued+=row.minimumTreasurePerGame;this.lastEvent='IKUKAN_TREASURE_HIT_MINIMUM_50000_TRACKED_SEPARATELY';}else{this.pendingTreasureAwardEvents+=1;this.lastEvent=`GT_STAGE_TREASURE_HIT_${this.stage}_AMOUNT_PENDING`;}}}
  beginNextSet(source){this.setNo+=1;this.gameInSet=0;this.remainingGames=GOLDEN_TIME_PROFILE.setGamesApprox;this.state='STAGE_PENDING_SELECTION_MODEL';this.result='UNRESOLVED';this.treasurePoints=0;this.battleContinuationPct=null;this.battleResult=null;this.battleSource=source;this.rushGameCount=0;this.rushRemainingGames=null;this.rushType=null;this.rushTypeAverageTreasure=null;this.rushResultSource='CONTINUATION_SET_START_MODEL_PENDING';this.stage=null;this.stageSource=null;this.stageTreasureHitEvents=0;this.lastStageTreasureHitGame=null;this.pendingTreasureAwardEvents=0;this.ikukanGameCount=0;this.ikukanRemainingGames=null;this.ikukanGuaranteedMinimumAccrued=0;}
  resolveTreasureBattle(){const pct=getTreasureContinuationPct(this.treasurePoints);this.battleContinuationPct=pct;if(pct==null){this.state='BATTLE_PENDING_UNVERIFIED_TREASURE_POINT';this.battleResult='UNRESOLVED';this.battleSource='NO_INTERPOLATION';this.lastEvent='GT_BATTLE_PENDING_EXACT_TREASURE_VALUE';return this.snapshot();}const win=rollTreasureContinuation(this.treasurePoints,this.rng);this.battleResult=win?'WIN':'LOSE';this.battleSource='VERIFIED_TREASURE_TABLE';if(win){this.result='CONTINUE';this.lastEvent='GT_TREASURE_BATTLE_WIN';this.beginNextSet('TREASURE_BATTLE_WIN');}else{this.state='ART_END_PENDING_RETURN';this.result='END';this.lastEvent='GT_TREASURE_BATTLE_LOSE';}return this.snapshot();}
  completeGame(){this.lastEvent=null;if(this.state==='LUPIN_RUSH_ACTIVE'){this.rushGameCount+=1;this.rushRemainingGames=Math.max(0,LUPIN_RUSH_PROFILE.games-this.rushGameCount);if(this.rushRemainingGames===0){this.state='RUSH_RESULT_PENDING';this.lastEvent='LUPIN_RUSH_4G_END_SELECTION_DISTRIBUTION_PENDING';}else this.lastEvent='LUPIN_RUSH_GAME';return this.snapshot();}if(this.state!=='ACTIVE_SET'){this.lastEvent=`GOLDEN_TIME_${this.state}`;return this.snapshot();}this.gameInSet+=1;this.remainingGames=Math.max(0,GOLDEN_TIME_PROFILE.setGamesApprox-this.gameInSet);this.processStageTreasure();if(this.remainingGames>0){if(!this.lastEvent)this.lastEvent='GOLDEN_TIME_GAME';return this.snapshot();}if(this.guaranteedStocks>0){this.guaranteedStocks-=1;this.beginNextSet('GUARANTEED_STOCK');this.lastEvent='GOLDEN_TIME_CONTINUE_BY_STOCK';return this.snapshot();}return this.resolveTreasureBattle();}
  snapshot(){return{state:this.state,setNo:this.setNo,gameInSet:this.gameInSet,remainingGames:this.remainingGames,guaranteedStocks:this.guaranteedStocks,entrySource:this.entrySource,result:this.result,lastEvent:this.lastEvent,treasurePoints:this.treasurePoints,battleContinuationPct:this.battleContinuationPct,battleResult:this.battleResult,battleSource:this.battleSource,rushGameCount:this.rushGameCount,rushRemainingGames:this.rushRemainingGames,rushType:this.rushType,rushTypeAverageTreasure:this.rushTypeAverageTreasure,rushResultSource:this.rushResultSource,rushProfile:LUPIN_RUSH_PROFILE,stage:this.stage,stageSource:this.stageSource,stageProfile:this.stage?getArtStage(this.stage):null,stageTreasureHitEvents:this.stageTreasureHitEvents,lastStageTreasureHitGame:this.lastStageTreasureHitGame,pendingTreasureAwardEvents:this.pendingTreasureAwardEvents,ikukanGameCount:this.ikukanGameCount,ikukanRemainingGames:this.ikukanRemainingGames,ikukanGuaranteedMinimumAccrued:this.ikukanGuaranteedMinimumAccrued,artStageProfile:ART_STAGE_PROFILE,profile:GOLDEN_TIME_PROFILE};}
}
