import { GOLDEN_TIME_PROFILE } from './golden-time-profile.js?v=step6i';
import { getTreasureContinuationPct, rollTreasureContinuation } from './treasure-profile.js?v=step6i';
import { LUPIN_RUSH_PROFILE, getLupinRushType } from './lupin-rush-profile.js?v=step6i';
import { ART_STAGE_PROFILE, getArtStage, rollStageTreasureHit } from './art-stage-profile.js?v=step6i';
import { ART_STAGE_SCENARIO_PROFILE, drawArtStageScenario, drawInitialInternalStage, drawStageUpgradeSteps, visibleStageFromInternal } from './art-stage-scenario-profile.js?v=step6i';
import { TREASURE_AWARD_PROFILE, rollOreNoNaWaLupinRush } from './treasure-award-profile.js?v=step6i';
import { EXTRA_BONUS_PROFILE, GOLD_RUSH_PROFILE, rollOneIn, rollGoldRushContinuation } from './extra-bonus-profile.js?v=step6i';

export class GoldenTimeSystem {
  constructor(rng,setting=1){this.rng=rng;this.setting=Number(setting);this.reset();}
  setSetting(setting){if(this.state!=='IDLE')return false;this.setting=Number(setting);return true;}
  reset(){this.state='IDLE';this.setNo=0;this.gameInSet=0;this.remainingGames=null;this.guaranteedStocks=0;this.entrySource=null;this.lastEvent=null;this.result='UNRESOLVED';this.treasurePoints=0;this.battleContinuationPct=null;this.battleResult=null;this.battleSource=null;this.rushGameCount=0;this.rushRemainingGames=null;this.rushType=null;this.rushTypeAverageTreasure=null;this.rushResultSource=null;this.stageScenario=null;this.stageScenarioSource=null;this.internalStageIndex=null;this.internalStage=null;this.stage=null;this.stageSource=null;this.lastStageUpgradeSteps=null;this.lastStageUpgradeGame=null;this.stageTreasureHitEvents=0;this.lastStageTreasureHitGame=null;this.pendingTreasureAwardEvents=0;this.verifiedMinimumAwardAccrued=0;this.lastNormalAwardFloorGame=null;this.ikukanGameCount=0;this.ikukanRemainingGames=null;this.ikukanGuaranteedMinimumAccrued=0;this.ikukanEntryGame=null;this.oreNoNaWaHits=0;this.lastOreNoNaWaGame=null;this.pendingExactTreasureAward=null;this.goldChanceBaseRemainingGames=null;this.goldChanceAddedGames=null;this.goldChanceSource=null;this.extraGameCount=0;this.extraTargetGames=null;this.extraRemainingGames=null;this.extraStockLotteryEvents=0;this.extraStockHits=0;this.extraResult='UNRESOLVED';this.extraSource=null;this.pendingGoldRush=false;this.goldRushGameCount=0;this.goldRushStocks=0;this.goldRushResult='UNRESOLVED';}
  start({guaranteedStocks=0,source='DEBUG_DIRECT_ENTRY'}={}){this.reset();this.state='LUPIN_RUSH_ACTIVE';this.setNo=1;this.guaranteedStocks=Math.max(0,Number(guaranteedStocks)||0);this.entrySource=source;this.lastEvent='LUPIN_RUSH_START';this.rushRemainingGames=LUPIN_RUSH_PROFILE.games;this.rushResultSource='PENDING_UNVERIFIED_SELECTION_DISTRIBUTION';this.stageScenario=drawArtStageScenario(this.setting,this.rng);this.stageScenarioSource='VERIFIED_SETTING_TABLE';return true;}
  addStocks(count,source='DEBUG_ONLY'){if(this.state==='IDLE')return false;const add=Math.max(0,Number(count)||0);this.guaranteedStocks+=add;this.lastEvent=`GT_STOCK_PLUS_${add}_${source}`;return true;}
  setTreasureForTest(points){if(this.state==='IDLE')return false;const pct=getTreasureContinuationPct(points);if(pct==null)return false;this.treasurePoints=Number(points);this.battleContinuationPct=pct;this.lastEvent=`DEBUG_TREASURE_SET_${points}`;return true;}
  chooseInitialStage(){const x=drawInitialInternalStage(this.stageScenario,this.rng);this.internalStageIndex=x.index;this.internalStage=x.key;this.stage=visibleStageFromInternal(x.key);this.stageSource='VERIFIED_SCENARIO_INITIAL_TABLE';this.lastStageUpgradeSteps=null;this.lastStageUpgradeGame=null;this.ikukanGameCount=0;this.ikukanRemainingGames=this.stage==='IKUKAN'?ART_STAGE_PROFILE.stages.IKUKAN.durationGames:null;this.ikukanGuaranteedMinimumAccrued=0;this.ikukanEntryGame=this.stage==='IKUKAN'?0:null;}
  applyLupinRushAverageForTest(type){if(this.state!=='RUSH_RESULT_PENDING')return false;const row=getLupinRushType(type);if(!row)return false;this.rushType=type;this.rushTypeAverageTreasure=row.averageTreasure;this.rushResultSource='DEBUG_APPLIED_VERIFIED_TYPE_AVERAGE_NOT_ACTUAL_DISTRIBUTION';this.treasurePoints=row.averageTreasure;this.battleContinuationPct=getTreasureContinuationPct(this.treasurePoints);this.chooseInitialStage();this.state='ACTIVE_SET';this.gameInSet=0;this.remainingGames=GOLDEN_TIME_PROFILE.setGamesApprox;this.lastEvent=`DEBUG_LUPIN_RUSH_${type}_AVERAGE_APPLIED_STAGE_AUTO_${this.internalStage}`;return true;}
  setStageForTest(stage){if(this.state!=='ACTIVE_SET')return false;const row=getArtStage(stage);if(!row)return false;this.stage=stage;this.internalStage=stage==='IKUKAN'?'IKUKAN':`${stage}_A`;this.internalStageIndex=ART_STAGE_SCENARIO_PROFILE.internalOrder.indexOf(this.internalStage);this.stageSource='DEBUG_OVERRIDE_VISIBLE_STAGE';this.ikukanGameCount=0;this.ikukanRemainingGames=row.special?row.durationGames:null;this.ikukanGuaranteedMinimumAccrued=0;this.ikukanEntryGame=row.special?this.gameInSet:null;this.lastEvent=`DEBUG_GT_STAGE_${stage}`;return true;}
  setGoldChanceAddedGamesForTest(games){if(this.state!=='GOLD_CHANCE_PENDING_UNVERIFIED_DISTRIBUTION')return false;const add=Math.max(0,Math.floor(Number(games)||0));this.goldChanceAddedGames=add;this.goldChanceSource='DEBUG_INJECTED_GOLD_CHANCE_RESULT_NOT_DISTRIBUTION';this.extraTargetGames=(this.goldChanceBaseRemainingGames??0)+add;this.extraRemainingGames=this.extraTargetGames;this.extraGameCount=0;this.extraResult='READY';this.state='EXTRA_BONUS_READY';this.lastEvent=`GOLD_CHANCE_RESULT_${add}G_EXTRA_TOTAL_${this.extraTargetGames}G`;return true;}
  startExtraBonus(source='VERIFIED_1M_TREASURE'){if(this.state!=='EXTRA_BONUS_READY')return false;this.state='EXTRA_BONUS_ACTIVE';this.extraSource=source;this.extraResult='ACTIVE';this.lastEvent=`EXTRA_BONUS_START_${this.extraTargetGames}G`;return true;}
  forceExtraSevenForTest(){if(this.state!=='EXTRA_BONUS_ACTIVE')return false;this.pendingGoldRush=true;this.state='GOLD_RUSH_ACTIVE';this.goldRushGameCount=0;this.goldRushStocks=0;this.goldRushResult='ACTIVE';this.extraResult='GOLD_RUSH';this.lastEvent='EXTRA_BONUS_7_ALIGNMENT_GOLD_RUSH_START';return true;}
  upgradeInternalStage(){if(this.stage==='IKUKAN'||this.internalStageIndex==null)return;const steps=drawStageUpgradeSteps(this.stageScenario,this.rng);const nextIndex=Math.min(ART_STAGE_SCENARIO_PROFILE.internalOrder.length-1,this.internalStageIndex+steps);this.lastStageUpgradeSteps=nextIndex-this.internalStageIndex;this.lastStageUpgradeGame=this.gameInSet;this.internalStageIndex=nextIndex;this.internalStage=ART_STAGE_SCENARIO_PROFILE.internalOrder[nextIndex];this.stage=visibleStageFromInternal(this.internalStage);this.stageSource='VERIFIED_10G_SCENARIO_UPGRADE';if(this.stage==='IKUKAN'){this.ikukanGameCount=0;this.ikukanRemainingGames=ART_STAGE_PROFILE.stages.IKUKAN.durationGames;this.ikukanGuaranteedMinimumAccrued=0;this.ikukanEntryGame=this.gameInSet;}this.lastEvent=`GT_STAGE_UP_${this.lastStageUpgradeSteps}_${this.internalStage}`;}
  processExactTreasureEvents(){if(rollOreNoNaWaLupinRush(this.rng)){this.oreNoNaWaHits+=1;this.lastOreNoNaWaGame=this.gameInSet;this.pendingExactTreasureAward=TREASURE_AWARD_PROFILE.oreNoNaWaLupinRush.awardPoints;this.treasurePoints=TREASURE_AWARD_PROFILE.oreNoNaWaLupinRush.awardPoints;this.battleContinuationPct=100;this.goldChanceBaseRemainingGames=this.remainingGames;this.state='GOLD_CHANCE_PENDING_UNVERIFIED_DISTRIBUTION';this.lastEvent=`ORE_NO_NA_WA_1M_GOLD_CHANCE_PENDING_BASE_${this.goldChanceBaseRemainingGames}G`;return true;}return false;}
  processStageTreasure(){if(!this.stage)return;const row=getArtStage(this.stage);if(!row)return;if(rollStageTreasureHit(this.stage,this.rng)){this.stageTreasureHitEvents+=1;this.lastStageTreasureHitGame=this.gameInSet;if(row.special){this.ikukanGameCount+=1;this.ikukanRemainingGames=Math.max(0,row.durationGames-this.ikukanGameCount);this.ikukanGuaranteedMinimumAccrued+=row.minimumTreasurePerGame;this.lastEvent='IKUKAN_TREASURE_MINIMUM_50000_ACCRUED_SEPARATELY';}else{this.pendingTreasureAwardEvents+=1;this.verifiedMinimumAwardAccrued+=TREASURE_AWARD_PROFILE.normalTAlignment.minimumPoints;this.lastNormalAwardFloorGame=this.gameInSet;this.lastEvent=`GT_STAGE_TREASURE_HIT_${this.stage}_VERIFIED_FLOOR_100K_AMOUNT_DISTRIBUTION_PENDING`;}}}
  beginNextSet(source){this.setNo+=1;this.gameInSet=0;this.remainingGames=GOLDEN_TIME_PROFILE.setGamesApprox;this.state='ACTIVE_SET';this.result='UNRESOLVED';this.treasurePoints=0;this.battleContinuationPct=null;this.battleResult=null;this.battleSource=source;this.rushGameCount=0;this.rushRemainingGames=null;this.rushType=null;this.rushTypeAverageTreasure=null;this.rushResultSource='CONTINUATION_SET_NO_NEW_LUPIN_RUSH_MODEL';this.stageTreasureHitEvents=0;this.lastStageTreasureHitGame=null;this.pendingTreasureAwardEvents=0;this.verifiedMinimumAwardAccrued=0;this.lastNormalAwardFloorGame=null;this.pendingExactTreasureAward=null;this.chooseInitialStage();this.lastEvent=`GT_NEXT_SET_STAGE_AUTO_${this.internalStage}`;}
  resolveTreasureBattle(){const pct=getTreasureContinuationPct(this.treasurePoints);this.battleContinuationPct=pct;if(pct==null){this.state='BATTLE_PENDING_UNVERIFIED_TREASURE_POINT';this.battleResult='UNRESOLVED';this.battleSource='NO_INTERPOLATION';this.lastEvent='GT_BATTLE_PENDING_EXACT_TREASURE_VALUE';return this.snapshot();}const win=rollTreasureContinuation(this.treasurePoints,this.rng);this.battleResult=win?'WIN':'LOSE';this.battleSource='VERIFIED_TREASURE_TABLE';if(win){this.result='CONTINUE';this.beginNextSet('TREASURE_BATTLE_WIN');this.lastEvent='GT_TREASURE_BATTLE_WIN_NEXT_SET_AUTO_STAGE';}else{this.state='ART_END_PENDING_RETURN';this.result='END';this.lastEvent='GT_TREASURE_BATTLE_LOSE';}return this.snapshot();}
  completeExtraGame(){this.extraGameCount+=1;this.extraRemainingGames=Math.max(0,(this.extraRemainingGames??0)-1);this.extraStockLotteryEvents+=1;let event='EXTRA_BONUS_GAME';if(rollOneIn(EXTRA_BONUS_PROFILE.artStockHitDenominator,this.rng)){this.extraStockHits+=1;this.guaranteedStocks+=1;event='EXTRA_BONUS_ART_STOCK_HIT_1PLUS_FLOOR';}if(rollOneIn(EXTRA_BONUS_PROFILE.goldRushHitDenominator,this.rng)){this.pendingGoldRush=true;this.state='GOLD_RUSH_ACTIVE';this.goldRushGameCount=0;this.goldRushStocks=0;this.goldRushResult='ACTIVE';this.lastEvent='EXTRA_BONUS_GOLD_RUSH_HIT';return this.snapshot();}if(this.extraRemainingGames===0){this.state='EXTRA_BONUS_END_PENDING_GT_RETURN';this.extraResult='END';this.lastEvent='EXTRA_BONUS_TARGET_GAMES_COMPLETE';return this.snapshot();}this.lastEvent=event;return this.snapshot();}
  completeGoldRushGame(){this.goldRushGameCount+=1;this.goldRushStocks+=GOLD_RUSH_PROFILE.redAlignmentMinimumStocks;this.guaranteedStocks+=GOLD_RUSH_PROFILE.redAlignmentMinimumStocks;if(this.goldRushGameCount>=GOLD_RUSH_PROFILE.initialGames&&!rollGoldRushContinuation(this.rng)){this.state=(this.extraRemainingGames??0)>0?'EXTRA_BONUS_ACTIVE':'EXTRA_BONUS_END_PENDING_GT_RETURN';this.goldRushResult='END_RETURN_EXTRA';this.pendingGoldRush=false;this.extraResult=this.state==='EXTRA_BONUS_ACTIVE'?'ACTIVE_RESUMED_AFTER_GOLD_RUSH':'END';this.lastEvent=this.state==='EXTRA_BONUS_ACTIVE'?'GOLD_RUSH_END_RESUME_EXTRA':'GOLD_RUSH_END_EXTRA_ALREADY_COMPLETE';return this.snapshot();}this.lastEvent='GOLD_RUSH_CONTINUE_STOCK_1PLUS';return this.snapshot();}
  completeGame(){this.lastEvent=null;if(this.state==='EXTRA_BONUS_ACTIVE')return this.completeExtraGame();if(this.state==='GOLD_RUSH_ACTIVE')return this.completeGoldRushGame();if(this.state==='LUPIN_RUSH_ACTIVE'){this.rushGameCount+=1;this.rushRemainingGames=Math.max(0,LUPIN_RUSH_PROFILE.games-this.rushGameCount);if(this.rushRemainingGames===0){this.state='RUSH_RESULT_PENDING';this.lastEvent='LUPIN_RUSH_4G_END_SELECTION_DISTRIBUTION_PENDING';}else this.lastEvent='LUPIN_RUSH_GAME';return this.snapshot();}if(this.state!=='ACTIVE_SET'){this.lastEvent=`GOLDEN_TIME_${this.state}`;return this.snapshot();}this.gameInSet+=1;this.remainingGames=Math.max(0,GOLDEN_TIME_PROFILE.setGamesApprox-this.gameInSet);if(this.processExactTreasureEvents())return this.snapshot();this.processStageTreasure();if(this.stage==='IKUKAN'&&this.ikukanRemainingGames===0&&this.remainingGames>0){this.state='IKUKAN_EXIT_PENDING_RETURN_STAGE_MODEL';this.lastEvent='IKUKAN_10G_END_RETURN_STAGE_UNVERIFIED';return this.snapshot();}if(this.remainingGames>0&&this.gameInSet%ART_STAGE_SCENARIO_PROFILE.upgradeIntervalGames===0&&this.stage!=='IKUKAN')this.upgradeInternalStage();if(this.remainingGames>0){if(!this.lastEvent)this.lastEvent='GOLDEN_TIME_GAME';return this.snapshot();}if(this.guaranteedStocks>0){this.guaranteedStocks-=1;this.beginNextSet('GUARANTEED_STOCK');this.lastEvent='GOLDEN_TIME_CONTINUE_BY_STOCK_NEXT_SET_AUTO_STAGE';return this.snapshot();}return this.resolveTreasureBattle();}
  snapshot(){return{state:this.state,setNo:this.setNo,gameInSet:this.gameInSet,remainingGames:this.remainingGames,guaranteedStocks:this.guaranteedStocks,entrySource:this.entrySource,result:this.result,lastEvent:this.lastEvent,treasurePoints:this.treasurePoints,battleContinuationPct:this.battleContinuationPct,battleResult:this.battleResult,battleSource:this.battleSource,rushGameCount:this.rushGameCount,rushRemainingGames:this.rushRemainingGames,rushType:this.rushType,rushTypeAverageTreasure:this.rushTypeAverageTreasure,rushResultSource:this.rushResultSource,rushProfile:LUPIN_RUSH_PROFILE,stageScenario:this.stageScenario,stageScenarioSource:this.stageScenarioSource,internalStageIndex:this.internalStageIndex,internalStage:this.internalStage,stage:this.stage,stageSource:this.stageSource,stageProfile:this.stage?getArtStage(this.stage):null,lastStageUpgradeSteps:this.lastStageUpgradeSteps,lastStageUpgradeGame:this.lastStageUpgradeGame,stageTreasureHitEvents:this.stageTreasureHitEvents,lastStageTreasureHitGame:this.lastStageTreasureHitGame,pendingTreasureAwardEvents:this.pendingTreasureAwardEvents,verifiedMinimumAwardAccrued:this.verifiedMinimumAwardAccrued,lastNormalAwardFloorGame:this.lastNormalAwardFloorGame,ikukanGameCount:this.ikukanGameCount,ikukanRemainingGames:this.ikukanRemainingGames,ikukanGuaranteedMinimumAccrued:this.ikukanGuaranteedMinimumAccrued,ikukanEntryGame:this.ikukanEntryGame,oreNoNaWaHits:this.oreNoNaWaHits,lastOreNoNaWaGame:this.lastOreNoNaWaGame,pendingExactTreasureAward:this.pendingExactTreasureAward,goldChanceBaseRemainingGames:this.goldChanceBaseRemainingGames,goldChanceAddedGames:this.goldChanceAddedGames,goldChanceSource:this.goldChanceSource,extraGameCount:this.extraGameCount,extraTargetGames:this.extraTargetGames,extraRemainingGames:this.extraRemainingGames,extraStockLotteryEvents:this.extraStockLotteryEvents,extraStockHits:this.extraStockHits,extraResult:this.extraResult,extraSource:this.extraSource,pendingGoldRush:this.pendingGoldRush,goldRushGameCount:this.goldRushGameCount,goldRushStocks:this.goldRushStocks,goldRushResult:this.goldRushResult,extraBonusProfile:EXTRA_BONUS_PROFILE,goldRushProfile:GOLD_RUSH_PROFILE,treasureAwardProfile:TREASURE_AWARD_PROFILE,artStageScenarioProfile:ART_STAGE_SCENARIO_PROFILE,artStageProfile:ART_STAGE_PROFILE,profile:GOLDEN_TIME_PROFILE};}
}
