import { drawWantedInitialTarget } from './wanted-profile.js?v=step6r';
import { HoldQueue } from './hold-queue.js?v=step6r';
import { drawCzLength, drawCzScenario } from './cz-profile.js?v=step6r';
import { RIZE_PROFILE, getRizeConfidence } from './rize-profile.js?v=step6r';
import { RAIUN_PROFILE, getRaiunHighProfile, rollRaiunHighEntry, rollShinRaiunUpgrade, rollRaiunArtCalibrated, rollShinRaiunLegendGate } from './raiun-profile.js?v=step6r';
import { RAIUN_POINT_MODEL, drawInitialRaiunPoints, rollRaiunPointAdd, drawRaiunPointAdd } from './raiun-point-model.js?v=step6r';
import { LEGEND_GATE_PROFILE, getLegendGateBenefit } from './legend-gate-profile.js?v=step6r';

const DIRECT_ZONE_EVENTS=new Set(['DOROBO_ZONE','FUJIKO_ZONE','SEVEN_ZONE']);
const SUPPORTED_CZ_TYPES=new Set(['DOROBO_ZONE','FUJIKO_ZONE']);

export class NormalSystem {
  constructor(rng,setting=1){
    const wantedTarget=drawWantedInitialTarget(rng);
    this.rng=rng;this.setting=Number(setting);this.mode='NORMAL';this.gameCount=0;this.wantedCount=0;this.wantedCycle='INITIAL';this.wantedTargetZone=wantedTarget.zone;this.wantedTargetGame=wantedTarget.game;this.wantedTargetDistribution=wantedTarget.distribution;this.wantedHardMaxGame=wantedTarget.hardMaxGame;this.wantedState='COUNTING';this.wantedEntrySource=null;this.wantedChanceGameCount=0;this.holdCapacity=null;this.holdQueue=null;this.lastConsumedHold=null;this.pendingReward=null;this.transitionSource=null;this.cz=null;this.rize=null;this.legendGate=null;
    const initialPoints=drawInitialRaiunPoints(rng);
    this.raiun={points:initialPoints,targetPoints:RAIUN_PROFILE.counter.targetPoints,counterModel:'CALIBRATED_EFFECTIVE_RATE',counterSource:RAIUN_POINT_MODEL.source,rawAddRate:RAIUN_POINT_MODEL.raw.publishedAddRateRange,effectiveAddDenominator:RAIUN_POINT_MODEL.calibrated.effectiveAddDenominator,averageInitialPoints:RAIUN_POINT_MODEL.raw.averageInitialPoints,averagePointsOnAdd:RAIUN_POINT_MODEL.raw.averagePointsPerAdd,publishedAverageGamesTo100:RAIUN_POINT_MODEL.raw.publishedAverageGamesTo100,lastPointAdd:0,pointAddEvents:0,state:'COUNTING',highLevel:null,highGameCount:0,highRemainingGames:null,highEntryDenominator:null,highExpectation:null,variant:null,modeGameCount:0,modeRemainingGames:null,result:'UNRESOLVED',resultSource:null,successModel:'NOT_IN_RAIUN_MODE',legendGateRate:null,legendGateHits:0,lastLegendGateGame:null};
    this.lastEvent='RAIUN_INITIAL_CALIBRATED';
  }
  setSetting(setting){this.setting=Number(setting);} closeWantedHolds(){this.holdCapacity=null;this.holdQueue=null;}
  startCz(type,source){if(!SUPPORTED_CZ_TYPES.has(type))return false;const totalGames=drawCzLength(this.setting,this.rng),scenario=drawCzScenario(this.setting,this.rng);this.mode=type;this.rize=null;this.legendGate=null;this.cz={type,state:'ACTIVE',result:'UNRESOLVED',resultSource:null,gameCount:0,totalGames,remainingGames:totalGames,scenario,lengthSource:'VERIFIED_SETTING_TABLE',scenarioSource:'VERIFIED_SETTING_TABLE',successModel:'UNIMPLEMENTED_PER_GAME_RATE_UNKNOWN',publishedOverallExpectation:type==='DOROBO_ZONE'?'39.6-43.2%':'58.8-63.2%',transitionSource:source};return true;}
  startSevenZone(source){this.mode='SEVEN_ZONE';this.rize=null;this.legendGate=null;this.cz={type:'SEVEN_ZONE',state:'ART_GUARANTEED',result:'SUCCESS',resultSource:'VERIFIED_ZONE_ENTRY_GUARANTEE',gameCount:null,totalGames:null,remainingGames:null,scenario:null,successModel:'GUARANTEED_ON_ENTRY',publishedOverallExpectation:'100%',transitionSource:source};this.pendingReward={type:'GOLDEN_TIME',source:'SEVEN_ZONE_ENTRY',guarantee:'ART_CONFIRMED',status:'PENDING_GOLDEN_TIME_IMPLEMENTATION'};this.lastEvent='ENTER_SEVEN_ZONE_ART_GUARANTEED';}
  startRizeZone(variant='RIZE',source='DEBUG_ONLY'){if(!['RIZE','SHIN_RIZE'].includes(variant))return false;this.mode='RIZE_ZONE';this.cz=null;this.legendGate=null;this.pendingReward=null;this.transitionSource=source;this.rize={type:'RIZE_ZONE',variant,state:'ACTIVE_PREMONITION',result:'UNRESOLVED',resultSource:null,background:'BLUE',backgroundConfidence:getRizeConfidence(variant,'BLUE'),entryRate:variant==='RIZE'?`1/${RIZE_PROFILE.entryRate}`:'UNVERIFIED_VARIANT_ENTRY_RATE',publishedOverallExpectation:variant==='RIZE'?`${RIZE_PROFILE.overallExpectation}%`:'BACKGROUND_TABLE_ONLY',duration:'UNVERIFIED',upgradeModel:'UNVERIFIED',transitionSource:source};this.lastEvent=`ENTER_${variant}`;return true;}
  setRizeBackgroundForTest(background){if(this.mode!=='RIZE_ZONE'||!this.rize||!RIZE_PROFILE.backgrounds.includes(background))return false;this.rize.background=background;this.rize.backgroundConfidence=getRizeConfidence(this.rize.variant,background);this.lastEvent=`DEBUG_RIZE_BACKGROUND_${background}`;return true;}
  resolveRizeForTest(result){if(this.mode!=='RIZE_ZONE'||!this.rize||!['SUCCESS','FAIL'].includes(result))return false;this.rize.result=result;this.rize.resultSource='DEBUG_ONLY';if(result==='SUCCESS'){this.rize.state='SUCCESS_PENDING_DESTINATION';this.pendingReward={type:'LB_OR_GT',source:`${this.rize.variant}_${this.rize.background}_DEBUG`,guarantee:'LB_OR_GT',status:'PENDING_DESTINATION_IMPLEMENTATION'};this.lastEvent='DEBUG_RIZE_SUCCESS_ROUTED';}else{this.rize.state='FAIL_PENDING_RETURN';this.pendingReward=null;this.lastEvent='DEBUG_RIZE_FAIL_ROUTED';}return true;}
  beginRaiunHigh(level='LOW',source='DEBUG_ONLY'){if(!['LOW','HIGH'].includes(level))return false;const p=getRaiunHighProfile(level);this.mode='RAIUN_HIGH';this.raiun.points=100;this.raiun.state='HIGH_ACTIVE';this.raiun.highLevel=level;this.raiun.highGameCount=0;this.raiun.highRemainingGames=RAIUN_PROFILE.high.totalGames;this.raiun.highEntryDenominator=p.denominator;this.raiun.highExpectation=p.expectation;this.raiun.variant=null;this.raiun.result='UNRESOLVED';this.raiun.entrySource=source;this.lastEvent=`RAIUN_HIGH_START_${level}`;return true;}
  seekRaiun100ForTest(level='LOW'){if(this.mode!=='NORMAL')return false;return this.beginRaiunHigh(level,'DEBUG_RAIUN_100');}
  startRaiunMode(source='HIGH_LOTTERY',forcedVariant=null){const variant=forcedVariant??(rollShinRaiunUpgrade(this.rng)?'SHIN_RAIUN':'RAIUN');this.mode='RAIUN_MODE';this.legendGate=null;this.raiun.state=variant==='SHIN_RAIUN'?'SHIN_ACTIVE_UNTIL_ART':'ACTIVE_20G';this.raiun.variant=variant;this.raiun.modeGameCount=0;this.raiun.modeRemainingGames=variant==='SHIN_RAIUN'?null:RAIUN_PROFILE.mode.normalGames;this.raiun.result='UNRESOLVED';this.raiun.resultSource=null;this.raiun.entrySource=source;this.raiun.artExpectation=variant==='RAIUN'?`${RAIUN_PROFILE.mode.artExpectation}%`:'ART_UNTIL_HIT';this.raiun.shinUpgradeRate=`${RAIUN_PROFILE.mode.shinUpgradeRate}%`;this.raiun.legendGateRate=variant==='SHIN_RAIUN'?`1/${RAIUN_PROFILE.mode.shinLegendGateDenominator}`:null;this.raiun.successModel=variant==='RAIUN'?RAIUN_PROFILE.mode.artModelSource:'VERIFIED_LEGEND_GATE_ONLY_ART_RATE_PENDING';this.raiun.artPerGameDenominator=variant==='RAIUN'?RAIUN_PROFILE.mode.calibratedPerGameDenominator:null;this.raiun.lastLegendGateGame=null;this.lastEvent=`ENTER_${variant}`;return true;}
  startRaiunModeForTest(variant='RAIUN'){if(this.mode!=='NORMAL'||!['RAIUN','SHIN_RAIUN'].includes(variant))return false;return this.startRaiunMode('DEBUG_DIRECT_ENTRY',variant);}
  resolveRaiunForTest(result){if(this.mode!=='RAIUN_MODE'||!['SUCCESS','FAIL'].includes(result))return false;if(this.raiun.variant==='SHIN_RAIUN'&&result==='FAIL')return false;this.raiun.result=result;this.raiun.resultSource='DEBUG_ONLY';if(result==='SUCCESS'){this.raiun.state='ART_SUCCESS_PENDING_GT';this.pendingReward={type:'GOLDEN_TIME',source:`${this.raiun.variant}_7_ALIGNMENT_DEBUG`,guarantee:'ART_CONFIRMED',status:'PENDING_GOLDEN_TIME_IMPLEMENTATION'};this.lastEvent='DEBUG_RAIUN_ART_SUCCESS';}else{this.raiun.state='FAIL_PENDING_RETURN';this.pendingReward=null;this.lastEvent='DEBUG_RAIUN_FAIL';}return true;}
  startLegendGate(source='DEBUG_DIRECT_ENTRY'){this.mode='LEGEND_GATE';this.cz=null;this.rize=null;this.pendingReward=null;this.transitionSource=source;this.legendGate={type:'LEGEND_GATE',state:'ACTIVE_STOCK_ZONE',entrySource:source,trigger:LEGEND_GATE_PROFILE.trigger,duration:LEGEND_GATE_PROFILE.duration,medalAcquisitionModel:LEGEND_GATE_PROFILE.medalAcquisitionModel,medals:0,minGtStocks:null,expectedSetRange:null,stockSource:'VERIFIED_MEDAL_MINIMUM_TABLE'};this.raiun.state='LEGEND_GATE_ENTERED';this.raiun.result='LEGEND_GATE';this.lastEvent='ENTER_LEGEND_GATE';return true;}
  startLegendGateForTest(){if(this.mode!=='NORMAL')return false;return this.startLegendGate('DEBUG_DIRECT_ENTRY');}
  setLegendGateMedalsForTest(medals){if(this.mode!=='LEGEND_GATE'||!this.legendGate)return false;const benefit=getLegendGateBenefit(medals);if(!benefit)return false;this.legendGate.medals=Number(medals);this.legendGate.minGtStocks=benefit.minGtStocks;this.legendGate.expectedSetRange=benefit.expectedSetRange;this.legendGate.state='MEDAL_RESULT_FIXED_DEBUG';this.pendingReward={type:'GOLDEN_TIME_STOCKS',source:`LEGEND_GATE_${medals}_MEDALS_DEBUG`,guarantee:`GT_STOCKS_${benefit.minGtStocks}_OR_MORE`,minStocks:benefit.minGtStocks,status:'PENDING_GOLDEN_TIME_STOCK_ENGINE'};this.lastEvent=`DEBUG_LEGEND_GATE_MEDALS_${medals}`;return true;}
  resolveCzForTest(result){if(!SUPPORTED_CZ_TYPES.has(this.mode)||!this.cz||!['SUCCESS','FAIL'].includes(result))return false;this.cz.result=result;this.cz.resultSource='DEBUG_ONLY';this.cz.remainingGames=0;if(result==='SUCCESS'){this.cz.state='SUCCESS_PENDING_DESTINATION';this.pendingReward={type:'LB_OR_GT',source:`${this.cz.type}_NUMBER_ALIGNMENT_DEBUG`,guarantee:'LB_OR_GT',status:'PENDING_DESTINATION_IMPLEMENTATION'};this.lastEvent=`DEBUG_${this.cz.type}_SUCCESS_ROUTED`;}else{this.cz.state='FAIL_PENDING_RETURN';this.pendingReward=null;this.lastEvent=`DEBUG_${this.cz.type}_FAIL_ROUTED`;}return true;}
  applyConsumedHold(hold){if(!hold?.reservedEvent)return false;if(DIRECT_ZONE_EVENTS.has(hold.reservedEvent)){this.wantedState='SUSPENDED';this.transitionSource=`HOLD_${hold.type}`;this.pendingReward=null;this.closeWantedHolds();if(SUPPORTED_CZ_TYPES.has(hold.reservedEvent)){this.startCz(hold.reservedEvent,this.transitionSource);this.lastEvent=`ENTER_${hold.reservedEvent}`;}else if(hold.reservedEvent==='SEVEN_ZONE')this.startSevenZone(this.transitionSource);return true;}this.pendingReward={type:hold.reservedEvent,source:`HOLD_${hold.type}`,guarantee:hold.guarantee,status:'PENDING_DESTINATION_IMPLEMENTATION'};this.transitionSource=`HOLD_${hold.type}`;this.lastEvent=`RESERVE_${hold.reservedEvent}`;return true;}
  advanceRaiunCounter(){if(this.raiun.state!=='COUNTING'||this.raiun.points>=100)return;this.raiun.lastPointAdd=0;if(rollRaiunPointAdd(this.rng)){const add=drawRaiunPointAdd(this.rng);this.raiun.lastPointAdd=add;this.raiun.pointAddEvents+=1;this.raiun.points=Math.min(100,this.raiun.points+add);this.lastEvent=`RAIUN_POINT_PLUS_${add}`;}if(this.raiun.points>=100){this.raiun.state='100PT_READY_HIGH_LEVEL_UNVERIFIED';this.lastEvent='RAIUN_100PT_REACHED_PENDING_LEVEL';}}
  completeGame(){this.lastEvent=null;this.lastConsumedHold=null;this.gameCount+=1;
    if(this.mode==='NORMAL'){this.wantedCount+=1;this.advanceRaiunCounter();if(this.wantedState==='COUNTING'&&this.wantedCount>=this.wantedTargetZone.min)this.wantedState='ARMED';if(this.wantedCount>=this.wantedTargetGame){this.mode='WANTED_CHANCE';this.wantedState='ACTIVE';this.wantedEntrySource='VERIFIED_UNIFORM_TARGET_GAME_WITHIN_SELECTED_32G_BAND';this.wantedChanceGameCount=0;this.holdCapacity=8;this.holdQueue=new HoldQueue(this.holdCapacity);this.holdQueue.fill();this.lastEvent='WANTED_CHANCE_START_VERIFIED_TARGET_GAME';}}
    else if(this.mode==='WANTED_CHANCE'){this.wantedChanceGameCount+=1;this.holdCapacity=8;if(!this.holdQueue){this.holdQueue=new HoldQueue(this.holdCapacity);this.holdQueue.fill();}const x=this.holdQueue.consumeAndRefill();this.lastConsumedHold=x.consumed;if(!this.applyConsumedHold(this.lastConsumedHold))this.lastEvent='WANTED_CHANCE_HOLD_CONSUME';}
    else if(SUPPORTED_CZ_TYPES.has(this.mode)){if(this.cz?.state==='ACTIVE'){this.cz.gameCount+=1;this.cz.remainingGames=Math.max(0,this.cz.totalGames-this.cz.gameCount);if(this.cz.remainingGames===0){this.cz.state='END_PENDING_VERIFIED_SUCCESS_MODEL';this.lastEvent=`${this.cz.type}_END_PENDING_MODEL`;}else this.lastEvent=`${this.cz.type}_GAME`;}else this.lastEvent=`${this.mode}_${this.cz?.state??'UNKNOWN'}`;}
    else if(this.mode==='SEVEN_ZONE')this.lastEvent='SEVEN_ZONE_ART_GUARANTEED_PENDING_GT';
    else if(this.mode==='RIZE_ZONE')this.lastEvent=`RIZE_ZONE_${this.rize?.state??'UNKNOWN'}`;
    else if(this.mode==='RAIUN_HIGH'){if(this.raiun.state==='HIGH_ACTIVE'){this.raiun.highGameCount+=1;this.raiun.highRemainingGames=Math.max(0,RAIUN_PROFILE.high.totalGames-this.raiun.highGameCount);if(rollRaiunHighEntry(this.raiun.highLevel,this.rng))this.startRaiunMode(`VERIFIED_${this.raiun.highLevel}_HIGH_LOTTERY`);else if(this.raiun.highRemainingGames===0){this.raiun.state='HIGH_MISS_PENDING_RETURN';this.lastEvent='RAIUN_HIGH_END_MISS';}else this.lastEvent='RAIUN_HIGH_GAME';}else this.lastEvent=`RAIUN_HIGH_${this.raiun.state}`;}
    else if(this.mode==='RAIUN_MODE'){if(['ACTIVE_20G','SHIN_ACTIVE_UNTIL_ART'].includes(this.raiun.state)){this.raiun.modeGameCount+=1;if(this.raiun.variant==='RAIUN'){this.raiun.modeRemainingGames=Math.max(0,RAIUN_PROFILE.mode.normalGames-this.raiun.modeGameCount);if(rollRaiunArtCalibrated(this.rng)){this.raiun.result='SUCCESS';this.raiun.resultSource='CALIBRATED_20G_23PCT_MODEL';this.raiun.state='ART_SUCCESS_PENDING_GT';this.pendingReward={type:'GOLDEN_TIME',source:'RAIUN_CALIBRATED_7_ALIGNMENT',guarantee:'ART_CONFIRMED',status:'PENDING_GOLDEN_TIME_IMPLEMENTATION'};this.lastEvent='RAIUN_ART_SUCCESS_CALIBRATED';}else if(this.raiun.modeRemainingGames===0){this.raiun.result='FAIL';this.raiun.resultSource='CALIBRATED_20G_23PCT_MODEL';this.raiun.state='FAIL_PENDING_RETURN';this.lastEvent='RAIUN_MODE_END_FAIL_CALIBRATED';}else this.lastEvent='RAIUN_MODE_GAME_CALIBRATED';}else{if(rollShinRaiunLegendGate(this.rng)){this.raiun.legendGateHits+=1;this.raiun.lastLegendGateGame=this.raiun.modeGameCount;this.raiun.resultSource='VERIFIED_1_OVER_88_9';this.startLegendGate('SHIN_RAIUN_VERIFIED_1_OVER_88_9');this.lastEvent='SHIN_RAIUN_LEGEND_GATE_ENTERED';}else this.lastEvent='SHIN_RAIUN_GAME_LEGEND_GATE_MISS_ART_MODEL_PENDING';}}else this.lastEvent=`RAIUN_MODE_${this.raiun.state}`;}
    else if(this.mode==='LEGEND_GATE')this.lastEvent=`LEGEND_GATE_${this.legendGate?.state??'UNKNOWN'}_DURATION_UNVERIFIED`;
    else this.lastEvent=`${this.mode}_GAME_UNIMPLEMENTED`;return this.snapshot();}
  injectHoldForTest(type){if(this.mode!=='WANTED_CHANCE'||!this.holdQueue)return false;this.holdQueue.injectNext(type);this.lastEvent=`DEBUG_HOLD_INJECT_${type}`;return true;}
  seekWantedForTest(){if(this.mode!=='NORMAL')return false;this.wantedCount=Math.max(0,this.wantedTargetGame-1);this.wantedState=this.wantedCount>=this.wantedTargetZone.min?'ARMED':'COUNTING';this.lastEvent='DEBUG_WANTED_SEEK_EXACT_TARGET';return true;}
  snapshot(){return{mode:this.mode,gameCount:this.gameCount,wantedCount:this.wantedCount,wantedCycle:this.wantedCycle,wantedTargetZone:{...this.wantedTargetZone},wantedTargetGame:this.wantedTargetGame,wantedTargetDistribution:this.wantedTargetDistribution,wantedHardMaxGame:this.wantedHardMaxGame,wantedState:this.wantedState,wantedEntrySource:this.wantedEntrySource,wantedChanceGameCount:this.wantedChanceGameCount,holdCapacity:this.holdCapacity,holdQueue:this.holdQueue?this.holdQueue.snapshot():[],lastConsumedHold:this.lastConsumedHold?{...this.lastConsumedHold}:null,pendingReward:this.pendingReward?{...this.pendingReward}:null,transitionSource:this.transitionSource,cz:this.cz?{...this.cz}:null,rize:this.rize?{...this.rize}:null,raiun:{...this.raiun},legendGate:this.legendGate?{...this.legendGate}:null,lastEvent:this.lastEvent};}
}
